# Generated by Django 5.2.17 on 2026-09-27 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Advertisement',
        ),
    ]
